# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/EditKey.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditKey(object):
    def setupUi(self, EditKey):
        EditKey.setObjectName("EditKey")
        EditKey.resize(632, 444)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EditKey.sizePolicy().hasHeightForWidth())
        EditKey.setSizePolicy(sizePolicy)
        EditKey.setMinimumSize(QtCore.QSize(632, 444))
        EditKey.setMaximumSize(QtCore.QSize(632, 444))
        EditKey.setModal(True)
        self.cancelsavebuttons = QtWidgets.QDialogButtonBox(EditKey)
        self.cancelsavebuttons.setGeometry(QtCore.QRect(330, 400, 291, 41))
        self.cancelsavebuttons.setOrientation(QtCore.Qt.Horizontal)
        self.cancelsavebuttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.cancelsavebuttons.setObjectName("cancelsavebuttons")
        self.maintabs = QtWidgets.QTabWidget(EditKey)
        self.maintabs.setGeometry(QtCore.QRect(10, 10, 611, 381))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maintabs.sizePolicy().hasHeightForWidth())
        self.maintabs.setSizePolicy(sizePolicy)
        self.maintabs.setMinimumSize(QtCore.QSize(611, 381))
        self.maintabs.setMaximumSize(QtCore.QSize(611, 381))
        self.maintabs.setObjectName("maintabs")
        self.appearance = QtWidgets.QWidget()
        self.appearance.setObjectName("appearance")
        self.lbl_4 = QtWidgets.QLabel(self.appearance)
        self.lbl_4.setGeometry(QtCore.QRect(300, 10, 151, 16))
        self.lbl_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_4.setObjectName("lbl_4")
        self.caption = QtWidgets.QLineEdit(self.appearance)
        self.caption.setGeometry(QtCore.QRect(110, 20, 101, 21))
        self.caption.setObjectName("caption")
        self.cssclass = QtWidgets.QLineEdit(self.appearance)
        self.cssclass.setGeometry(QtCore.QRect(40, 130, 221, 19))
        self.cssclass.setObjectName("cssclass")
        self.extracaptions = QtWidgets.QTableWidget(self.appearance)
        self.extracaptions.setGeometry(QtCore.QRect(300, 30, 261, 121))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.extracaptions.setFont(font)
        self.extracaptions.setShowGrid(True)
        self.extracaptions.setRowCount(0)
        self.extracaptions.setColumnCount(2)
        self.extracaptions.setObjectName("extracaptions")
        item = QtWidgets.QTableWidgetItem()
        self.extracaptions.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.extracaptions.setHorizontalHeaderItem(1, item)
        self.extracaptions.horizontalHeader().setCascadingSectionResizes(False)
        self.extracaptions.horizontalHeader().setStretchLastSection(True)
        self.extracaptions.verticalHeader().setVisible(False)
        self.extracaptions.verticalHeader().setStretchLastSection(False)
        self.lbl_3 = QtWidgets.QLabel(self.appearance)
        self.lbl_3.setGeometry(QtCore.QRect(40, 90, 191, 41))
        self.lbl_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_3.setWordWrap(True)
        self.lbl_3.setObjectName("lbl_3")
        self.lbl_1 = QtWidgets.QLabel(self.appearance)
        self.lbl_1.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.lbl_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_1.setObjectName("lbl_1")
        self.style = QtWidgets.QPlainTextEdit(self.appearance)
        self.style.setGeometry(QtCore.QRect(20, 190, 541, 131))
        self.style.setObjectName("style")
        self.lbl_5 = QtWidgets.QLabel(self.appearance)
        self.lbl_5.setGeometry(QtCore.QRect(40, 170, 291, 16))
        self.lbl_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_5.setObjectName("lbl_5")
        self.lbl_6 = QtWidgets.QLabel(self.appearance)
        self.lbl_6.setGeometry(QtCore.QRect(20, 320, 541, 16))
        self.lbl_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_6.setObjectName("lbl_6")
        self.lbl_2 = QtWidgets.QLabel(self.appearance)
        self.lbl_2.setGeometry(QtCore.QRect(20, 50, 81, 16))
        self.lbl_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_2.setObjectName("lbl_2")
        self.width = QtWidgets.QDoubleSpinBox(self.appearance)
        self.width.setGeometry(QtCore.QRect(110, 50, 81, 24))
        self.width.setDecimals(1)
        self.width.setMinimum(0.1)
        self.width.setSingleStep(0.1)
        self.width.setProperty("value", 1.0)
        self.width.setObjectName("width")
        self.deletecaption = QtWidgets.QPushButton(self.appearance)
        self.deletecaption.setGeometry(QtCore.QRect(530, 150, 31, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.deletecaption.setFont(font)
        self.deletecaption.setDefault(False)
        self.deletecaption.setFlat(False)
        self.deletecaption.setObjectName("deletecaption")
        self.addcaption = QtWidgets.QPushButton(self.appearance)
        self.addcaption.setGeometry(QtCore.QRect(500, 150, 31, 21))
        self.addcaption.setDefault(False)
        self.addcaption.setFlat(False)
        self.addcaption.setObjectName("addcaption")
        self.maintabs.addTab(self.appearance, "")
        self.action = QtWidgets.QWidget()
        self.action.setObjectName("action")
        self.actiontabs = QtWidgets.QTabWidget(self.action)
        self.actiontabs.setGeometry(QtCore.QRect(20, 20, 571, 321))
        self.actiontabs.setObjectName("actiontabs")
        self.single = QtWidgets.QWidget()
        self.single.setObjectName("single")
        self.actiontabs.addTab(self.single, "")
        self.double = QtWidgets.QWidget()
        self.double.setObjectName("double")
        self.actiontabs.addTab(self.double, "")
        self.long = QtWidgets.QWidget()
        self.long.setObjectName("long")
        self.actiontabs.addTab(self.long, "")
        self.maintabs.addTab(self.action, "")

        self.retranslateUi(EditKey)
        self.maintabs.setCurrentIndex(0)
        self.actiontabs.setCurrentIndex(0)
        self.cancelsavebuttons.accepted.connect(EditKey.accept)
        self.cancelsavebuttons.rejected.connect(EditKey.reject)
        QtCore.QMetaObject.connectSlotsByName(EditKey)
        EditKey.setTabOrder(self.maintabs, self.caption)
        EditKey.setTabOrder(self.caption, self.width)
        EditKey.setTabOrder(self.width, self.cssclass)
        EditKey.setTabOrder(self.cssclass, self.extracaptions)
        EditKey.setTabOrder(self.extracaptions, self.addcaption)
        EditKey.setTabOrder(self.addcaption, self.deletecaption)
        EditKey.setTabOrder(self.deletecaption, self.style)
        EditKey.setTabOrder(self.style, self.actiontabs)

    def retranslateUi(self, EditKey):
        _translate = QtCore.QCoreApplication.translate
        EditKey.setWindowTitle(_translate("EditKey", "Edit key properties"))
        self.lbl_4.setText(_translate("EditKey", "Additional captions:"))
        item = self.extracaptions.horizontalHeaderItem(0)
        item.setText(_translate("EditKey", "CSS class"))
        item = self.extracaptions.horizontalHeaderItem(1)
        item.setText(_translate("EditKey", "Caption"))
        self.lbl_3.setText(_translate("EditKey", "Additional CSS classes, separated by spaces:"))
        self.lbl_1.setText(_translate("EditKey", "Caption:"))
        self.lbl_5.setText(_translate("EditKey", "CSS StyleSheet specific to this key:"))
        self.lbl_6.setText(_translate("EditKey", "(Better to add CSS class and put style info in the keyboard stylesheet)"))
        self.lbl_2.setText(_translate("EditKey", "Key width:"))
        self.deletecaption.setText(_translate("EditKey", "-"))
        self.addcaption.setText(_translate("EditKey", "+"))
        self.maintabs.setTabText(self.maintabs.indexOf(self.appearance), _translate("EditKey", "Appearance"))
        self.actiontabs.setTabText(self.actiontabs.indexOf(self.single), _translate("EditKey", "Single Tap"))
        self.actiontabs.setTabText(self.actiontabs.indexOf(self.double), _translate("EditKey", "Double Tap"))
        self.actiontabs.setTabText(self.actiontabs.indexOf(self.long), _translate("EditKey", "Press and hold"))
        self.maintabs.setTabText(self.maintabs.indexOf(self.action), _translate("EditKey", "Action"))
