# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/KeyActions.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KeyActions(object):
    def setupUi(self, KeyActions):
        KeyActions.setObjectName("KeyActions")
        KeyActions.resize(560, 290)
        KeyActions.setWindowTitle("")
        self.view_thenview = QtWidgets.QComboBox(KeyActions)
        self.view_thenview.setGeometry(QtCore.QRect(180, 220, 131, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.view_thenview.setFont(font)
        self.view_thenview.setObjectName("view_thenview")
        self.lbl_16 = QtWidgets.QLabel(KeyActions)
        self.lbl_16.setGeometry(QtCore.QRect(330, 210, 61, 20))
        self.lbl_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_16.setObjectName("lbl_16")
        self.send = QtWidgets.QCheckBox(KeyActions)
        self.send.setGeometry(QtCore.QRect(30, 20, 151, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.send.setFont(font)
        self.send.setObjectName("send")
        self.send_printable = QtWidgets.QCheckBox(KeyActions)
        self.send_printable.setGeometry(QtCore.QRect(120, 110, 101, 20))
        self.send_printable.setObjectName("send_printable")
        self.view_until = QtWidgets.QLineEdit(KeyActions)
        self.view_until.setGeometry(QtCore.QRect(230, 250, 71, 21))
        self.view_until.setObjectName("view_until")
        self.keyboard = QtWidgets.QCheckBox(KeyActions)
        self.keyboard.setGeometry(QtCore.QRect(310, 180, 211, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.keyboard.setFont(font)
        self.keyboard.setObjectName("keyboard")
        self.view_name = QtWidgets.QComboBox(KeyActions)
        self.view_name.setGeometry(QtCore.QRect(50, 190, 131, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.view_name.setFont(font)
        self.view_name.setObjectName("view_name")
        self.lbl_12 = QtWidgets.QLabel(KeyActions)
        self.lbl_12.setGeometry(QtCore.QRect(30, 250, 191, 21))
        self.lbl_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_12.setWordWrap(True)
        self.lbl_12.setObjectName("lbl_12")
        self.modifier_keycode = QtWidgets.QLineEdit(KeyActions)
        self.modifier_keycode.setGeometry(QtCore.QRect(400, 50, 101, 21))
        self.modifier_keycode.setObjectName("modifier_keycode")
        self.lbl_13 = QtWidgets.QLabel(KeyActions)
        self.lbl_13.setGeometry(QtCore.QRect(310, 50, 81, 16))
        self.lbl_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_13.setObjectName("lbl_13")
        self.lbl_15 = QtWidgets.QLabel(KeyActions)
        self.lbl_15.setGeometry(QtCore.QRect(310, 110, 81, 16))
        self.lbl_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_15.setObjectName("lbl_15")
        self.lbl_10 = QtWidgets.QLabel(KeyActions)
        self.lbl_10.setGeometry(QtCore.QRect(30, 50, 81, 16))
        self.lbl_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_10.setObjectName("lbl_10")
        self.send_keycode = QtWidgets.QLineEdit(KeyActions)
        self.send_keycode.setGeometry(QtCore.QRect(120, 50, 101, 21))
        self.send_keycode.setObjectName("send_keycode")
        self.modifier_action = QtWidgets.QComboBox(KeyActions)
        self.modifier_action.setGeometry(QtCore.QRect(400, 110, 91, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.modifier_action.setFont(font)
        self.modifier_action.setObjectName("modifier_action")
        self.modifier_action.addItem("")
        self.modifier_action.addItem("")
        self.modifier_printable = QtWidgets.QCheckBox(KeyActions)
        self.modifier_printable.setGeometry(QtCore.QRect(400, 140, 111, 20))
        self.modifier_printable.setObjectName("modifier_printable")
        self.view = QtWidgets.QCheckBox(KeyActions)
        self.view.setGeometry(QtCore.QRect(30, 160, 181, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.view.setFont(font)
        self.view.setObjectName("view")
        self.keyboard_name = QtWidgets.QLineEdit(KeyActions)
        self.keyboard_name.setGeometry(QtCore.QRect(400, 210, 101, 21))
        self.keyboard_name.setObjectName("keyboard_name")
        self.send_name = QtWidgets.QLineEdit(KeyActions)
        self.send_name.setGeometry(QtCore.QRect(120, 80, 101, 21))
        self.send_name.setObjectName("send_name")
        self.modifier = QtWidgets.QCheckBox(KeyActions)
        self.modifier.setGeometry(QtCore.QRect(310, 20, 161, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.modifier.setFont(font)
        self.modifier.setObjectName("modifier")
        self.view_until_checkbox = QtWidgets.QCheckBox(KeyActions)
        self.view_until_checkbox.setGeometry(QtCore.QRect(50, 220, 131, 20))
        self.view_until_checkbox.setObjectName("view_until_checkbox")
        self.modifier_name = QtWidgets.QLineEdit(KeyActions)
        self.modifier_name.setGeometry(QtCore.QRect(400, 80, 101, 21))
        self.modifier_name.setObjectName("modifier_name")
        self.lbl_14 = QtWidgets.QLabel(KeyActions)
        self.lbl_14.setGeometry(QtCore.QRect(310, 80, 81, 16))
        self.lbl_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_14.setObjectName("lbl_14")
        self.lbl_11 = QtWidgets.QLabel(KeyActions)
        self.lbl_11.setGeometry(QtCore.QRect(30, 80, 81, 16))
        self.lbl_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_11.setObjectName("lbl_11")
        self.send_wiz = QtWidgets.QPushButton(KeyActions)
        self.send_wiz.setGeometry(QtCore.QRect(220, 50, 41, 21))
        self.send_wiz.setObjectName("send_wiz")
        self.modifier_wiz = QtWidgets.QPushButton(KeyActions)
        self.modifier_wiz.setGeometry(QtCore.QRect(500, 50, 41, 21))
        self.modifier_wiz.setObjectName("modifier_wiz")

        self.retranslateUi(KeyActions)
        QtCore.QMetaObject.connectSlotsByName(KeyActions)
        KeyActions.setTabOrder(self.send, self.send_keycode)
        KeyActions.setTabOrder(self.send_keycode, self.send_wiz)
        KeyActions.setTabOrder(self.send_wiz, self.send_name)
        KeyActions.setTabOrder(self.send_name, self.send_printable)
        KeyActions.setTabOrder(self.send_printable, self.view)
        KeyActions.setTabOrder(self.view, self.view_name)
        KeyActions.setTabOrder(self.view_name, self.view_until_checkbox)
        KeyActions.setTabOrder(self.view_until_checkbox, self.view_thenview)
        KeyActions.setTabOrder(self.view_thenview, self.view_until)
        KeyActions.setTabOrder(self.view_until, self.modifier)
        KeyActions.setTabOrder(self.modifier, self.modifier_keycode)
        KeyActions.setTabOrder(self.modifier_keycode, self.modifier_wiz)
        KeyActions.setTabOrder(self.modifier_wiz, self.modifier_name)
        KeyActions.setTabOrder(self.modifier_name, self.modifier_action)
        KeyActions.setTabOrder(self.modifier_action, self.modifier_printable)
        KeyActions.setTabOrder(self.modifier_printable, self.keyboard)
        KeyActions.setTabOrder(self.keyboard, self.keyboard_name)

    def retranslateUi(self, KeyActions):
        _translate = QtCore.QCoreApplication.translate
        self.lbl_16.setText(_translate("KeyActions", "name:"))
        self.send.setText(_translate("KeyActions", "Send keypress"))
        self.send_printable.setText(_translate("KeyActions", "printable"))
        self.keyboard.setText(_translate("KeyActions", "Jump to other keyboard"))
        self.lbl_12.setText(_translate("KeyActions", "After keyname matches:"))
        self.lbl_13.setText(_translate("KeyActions", "keycode:"))
        self.lbl_15.setText(_translate("KeyActions", "action:"))
        self.lbl_10.setText(_translate("KeyActions", "keycode:"))
        self.modifier_action.setItemText(0, _translate("KeyActions", "toggle"))
        self.modifier_action.setItemText(1, _translate("KeyActions", "lock"))
        self.modifier_printable.setText(_translate("KeyActions", "printable"))
        self.view.setText(_translate("KeyActions", "Jump to other view"))
        self.modifier.setText(_translate("KeyActions", "Be a modifier key"))
        self.view_until_checkbox.setText(_translate("KeyActions", "Then jump to"))
        self.lbl_14.setText(_translate("KeyActions", "name:"))
        self.lbl_11.setText(_translate("KeyActions", "name:"))
        self.send_wiz.setText(_translate("KeyActions", "wiz"))
        self.modifier_wiz.setText(_translate("KeyActions", "wiz"))
